<?xml version="1.0"?>
<!-- Author:  Raul Cruz-Oliver, rcruzoliver@student.ethz.ch -->
<!-- Date, place:  November 2023, Butikkon, CH -->

<robot name="printer_v1" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Define properties -->
  <!-- <xacro:property name="pi" value="3.1415926535" />  checked, does not need to redefine in humble-->

  <xacro:property name="granite_size_x" value="0.4" /> <!-- checked -->
  <xacro:property name="granite_size_y" value="0.4" /> <!-- checked -->
  <xacro:property name="granite_size_z" value="0.03" /> <!-- checked -->

  <xacro:property name="base_size_x" value="0.35" /> <!-- checked -->
  <xacro:property name="base_size_y" value="0.35" /> <!-- checked -->
  <xacro:property name="base_size_z" value="0.015" /> <!-- checked -->

  <xacro:property name="frame_size_x" value="0.3" /> <!-- checked -->
  <xacro:property name="frame_size_y" value="-0.2" /> <!-- checked -->
  <xacro:property name="frame_size_z" value="0.25" /> <!-- checked -->
  <xacro:property name="frame_relative_postion" value="0.1925" /> <!-- checked -->
  <xacro:property name="frame_mesh_xyz" value="-0.155 -0.2090 0" /> <!-- approx -->
  <xacro:property name="frame_mesh_rpy" value="0 0 0" /> <!-- approx -->

  <xacro:property name="base_y_axis_size_x" value="0.06" /> <!-- approx -->
  <xacro:property name="base_y_axis_size_y" value="0.18" /> <!-- approx -->
  <xacro:property name="base_y_axis_size_z" value="0.01" /> <!-- approx -->

  <xacro:property name="carriage_y_axis_size_x" value="0.085" /> <!-- approx -->
  <xacro:property name="carriage_y_axis_size_y" value="0.11" /> <!-- approx -->
  <xacro:property name="carriage_y_axis_size_z" value="0.010" /> <!-- approx -->

  <xacro:property name="carriage_x_axis_size_x" value="0.11" />  <!-- approx -->
  <xacro:property name="carriage_x_axis_size_y" value="0.085" />  <!-- approx -->
  <xacro:property name="carriage_x_axis_size_z" value="0.02" />  <!-- approx -->

  <xacro:property name="base_x_axis_size_x" value="0.16" /> <!-- approx -->
  <xacro:property name="base_x_axis_size_y" value="0.06" /> <!-- approx -->
  <xacro:property name="base_x_axis_size_z" value="0.01" /> <!-- approx -->

  <xacro:property name="bed_size_x" value="0.175" /> <!-- approx -->
  <xacro:property name="bed_size_y" value="0.175" /> <!-- approx -->
  <xacro:property name="bed_size_z" value="0.005" /> <!-- approx -->

  <xacro:property name="carriage_z_axis_size_x" value="0.065" /> <!-- approx -->
  <xacro:property name="carriage_z_axis_size_y" value="0.025" /> <!-- approx -->
  <xacro:property name="carriage_z_axis_size_z" value="0.07" /> <!-- approx -->

  <xacro:property name="base_z_axis_size_x" value="0.04" /> <!-- approx -->
  <xacro:property name="base_z_axis_size_y" value="0.01" /> <!-- approx -->
  <xacro:property name="base_z_axis_size_z" value="0.08" /> <!-- approx -->

  <xacro:property name="printhead_size_x" value="0.02" /> <!-- approx -->
  <xacro:property name="printhead_size_y" value="0.02" /> <!-- approx -->
  <xacro:property name="printhead_size_z" value="0.15" /> <!-- approx -->

  <xacro:property name="printhead_mesh_xyz" value="0 0 0" /> <!-- approx -->
  <xacro:property name="printhead_mesh_rpy" value="0 0 0" /> <!-- approx -->


  <!-- Links-->
  
 <link name="granite">
    <pose>0 0 0 0 0 0</pose>

    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${granite_size_x} ${granite_size_y} ${granite_size_z}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${granite_size_x} ${granite_size_y} ${granite_size_z}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.050" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <link name="base">
    <visual>
      <geometry>
        <box size="${base_size_x} ${base_size_y} ${base_size_z}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.050" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>
  
  <link name="frame">
    <visual>
      <!-- <origin xyz="0 0 ${frame_size_z/2}" /> -->
      <origin xyz="${frame_mesh_xyz}" rpy="${frame_mesh_rpy}"/>
      <geometry>
        <!-- <box size="${frame_size_x} ${frame_size_y} ${frame_size_z}"/> -->
        <mesh filename="package://kr_rviz_demo/meshes/frame.stl"/>
        <scale>0.1 0.1 0.1</scale>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
      </material>
    </visual>
    <collision>
      <!-- <origin xyz="0 0 ${frame_size_z/2}" /> -->
      <origin xyz="${frame_mesh_xyz}" rpy="${frame_mesh_rpy}"/>
      <geometry>
        <!-- <box size="${frame_size_x} ${frame_size_y} ${frame_size_z}" /> -->
        <mesh filename="package://kr_rviz_demo/meshes/frame.stl"/>
        <scale>0.1 0.1 0.1</scale>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <link name="base_y_axis">
    <visual>
      <origin xyz="0 0 ${base_y_axis_size_z/2}" />
      <geometry>
        <box size="${base_y_axis_size_x} ${base_y_axis_size_y} ${base_y_axis_size_z}"/>
      </geometry>
      <material name="grey">
        <color rgba="1 0 0 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_y_axis_size_z/2}" />
      <geometry>
        <box size="${base_y_axis_size_x} ${base_y_axis_size_y} ${base_y_axis_size_z}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <link name="carriage_y_axis">
    <visual>
      <origin xyz="0 0 ${carriage_y_axis_size_z/2}" />
      <geometry>
        <box size="${carriage_y_axis_size_x} ${carriage_y_axis_size_y} ${carriage_y_axis_size_z}"/>
      </geometry>
      <material name="grey">
        <color rgba="1 0 0 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${carriage_y_axis_size_z/2}" />
      <geometry>
        <box size="${carriage_y_axis_size_x} ${carriage_y_axis_size_y} ${carriage_y_axis_size_z}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <link name="carriage_x_axis">
    <visual>
      <origin xyz="0 0 ${carriage_x_axis_size_z/2}" />
      <geometry>
        <box size="${carriage_x_axis_size_x} ${carriage_x_axis_size_y} ${carriage_x_axis_size_z}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${carriage_x_axis_size_z/2}" />
      <geometry>
        <box size="${carriage_x_axis_size_x} ${carriage_x_axis_size_y} ${carriage_x_axis_size_z}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <link name="base_x_axis">
    <visual>
      <origin xyz="0 0 ${base_x_axis_size_z/2}" />
      <geometry>
        <box size="${base_x_axis_size_x} ${base_x_axis_size_y} ${base_x_axis_size_z}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_x_axis_size_z/2}" />
      <geometry>
        <box size="${base_x_axis_size_x} ${base_x_axis_size_y} ${base_x_axis_size_z}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>
  
  <link name="bed">
    <visual>
      <origin xyz="0 0 ${bed_size_z/2}" />
      <geometry>
        <box size="${bed_size_x} ${bed_size_y} ${bed_size_z}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.5 0.5 0.5 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${bed_size_z/2}" />
      <geometry>
        <box size="${bed_size_x} ${bed_size_y} ${bed_size_z}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <link name="carriage_z_axis">
    <visual>
      <origin xyz="0 ${-carriage_z_axis_size_y/2} 0" />
      <geometry>
        <box size="${carriage_z_axis_size_x} ${carriage_z_axis_size_y} ${carriage_z_axis_size_z}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 ${-carriage_z_axis_size_y/2} 0" />
      <geometry>
        <box size="${carriage_z_axis_size_x} ${carriage_z_axis_size_y} ${carriage_z_axis_size_z}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <link name="base_z_axis">
    <visual>
      <origin xyz="0 ${-base_z_axis_size_y} 0" />
      <geometry>
        <box size="${base_z_axis_size_x} ${-base_z_axis_size_y} ${base_z_axis_size_z}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 ${-base_z_axis_size_y} 0" />
      <geometry>
        <box size="${base_z_axis_size_x} ${-base_z_axis_size_y} ${base_z_axis_size_z}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <link name="printhead">
    <visual>
      <origin xyz="${printhead_mesh_xyz}" rpy="${printhead_mesh_rpy}" />
      <geometry>
        <box size="${printhead_size_x} ${printhead_size_y} ${printhead_size_z}"/> 
      </geometry>
      <material name="blue">
        <color rgba="0.5 0.5 0.5 1" />
      </material>
      
    </visual>
    <collision>
      <origin xyz="0 ${-printhead_size_y/2} 0" />
      <geometry>
        <box size="${printhead_size_x} ${printhead_size_y} ${printhead_size_z}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <!--
-->

  <!-- Joints -->

  <joint name="granite_to_base" type="fixed">
    <origin xyz="0.0 0.0 ${granite_size_z/2}" rpy="0 0 0" />
    <parent link="granite" />
    <child link="base" />
  </joint>

  <joint name="base_to_frame" type="fixed">
    <origin xyz="0.0 ${0.1925*base_size_y} ${base_size_z/2}" rpy="0 0 0" />  <!-- approx -->
    <parent link="base" />
    <child link="frame" />
  </joint>

  <joint name="base_to_base_y_axis" type="fixed">
    <origin xyz="0.0 ${0*base_size_y} ${base_size_z/2}" rpy="0 0 0" /> 
    <parent link="base" />
    <child link="base_y_axis" />
  </joint>

  <joint name="base_y_axis_to_carriage_y_axis" type="prismatic">
    <origin xyz="0.0 0.0 ${base_y_axis_size_z}" rpy="0 0 0" />
    <parent link="base_y_axis" />
    <child link="carriage_y_axis" />
    <axis xyz="0 1 0"/>
    <limit lower="-0.01" upper="0.01" effort="10" velocity="1"/>
  </joint>

  <joint name="carriage_y_axis_to_carriage_x_axis" type="fixed">
    <origin xyz="0.0 0.0 ${carriage_y_axis_size_z}" rpy="0 0 0" />
    <parent link="carriage_y_axis" />
    <child link="carriage_x_axis" />
  </joint>

  <joint name="carriage_x_axis_to_base_x_axis" type="prismatic">
    <origin xyz="0.0 0.0 ${carriage_x_axis_size_z}" rpy="0 0 0" />
    <parent link="carriage_x_axis" />
    <child link="base_x_axis" />
    <axis xyz="1 0 0"/>
    <limit lower="-0.01" upper="0.01" effort="10" velocity="1"/>
  </joint>

  <joint name="base_x_axis_to_bed" type="fixed">
    <origin xyz="0.0 0.0 ${base_x_axis_size_z}" rpy="0 0 0" />
    <parent link="base_x_axis" />
    <child link="bed" />
  </joint>

  <joint name="frame_to_carriage_z_axis" type="fixed">
    <origin xyz="0.0 ${0.20*frame_size_y} ${1*frame_size_z}" rpy="0 0 0" />
    <parent link="frame" />
    <child link="carriage_z_axis" />
  </joint>

  <joint name="carriage_z_axis_to_base_z_axis" type="prismatic">
    <origin xyz="0.0 ${-2*carriage_z_axis_size_y} 0" rpy="0 0 0" />
    <parent link="carriage_z_axis" />
    <child link="base_z_axis" />
    <axis xyz="0 0 1"/>
    <limit lower="-0.01" upper="0.01" effort="100" velocity="0.1"/>
  </joint>

  <joint name="base_z_axis_printhead" type="fixed">
    <origin xyz="0.0 ${-2*base_z_axis_size_y} 0" rpy="0 0 0" />
    <parent link="base_z_axis" />
    <child link="printhead" />
  </joint>

<!--
-->
  


</robot>
